export default function (plop) {
  /**
   * Set custom helpers for Plop.js
   * These helpers can be used in your generators and templates.
   * For example, you can create a PascalCase helper to convert a string to PascalCase.
   * Input:
   * + the test
   * + TheTest
   * + the-test
   * + theTest
   * + THE TEST
   */

  /**
   * output: TheTest
   */
  function coverStringToPascalCase(str) {
    return str.replace(/(?:^|\s|-)(\w)/g, (match, letter) => letter.toUpperCase());
  }
  function coverStringUpperSnakeCase(str) {
    return str
      .replace(/\s+/g, '_')
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/([A-Z])([A-Z][a-z])/g, '$1_$2')
      .toUpperCase();
  }
  function coverStringCapitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  plop.addHelper(
    'classify',
    (str) => str.charAt(0).toUpperCase() + str.slice(1),
  );

  /**
   * output: the-test
   */
  plop.addHelper('dasherize', (str) => str.replace(/([A-Z])/g, '-$1').toLowerCase());

  /**
   * output: theTest
   */
  plop.addHelper('underscore', (str) => str.replace(/([A-Z])/g, '_$1').toLowerCase());

  /**
   * output: THE_TEST
   */
  plop.setHelper('upperSnakeCase', (text) => {
    return text
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/([A-Z])([A-Z][a-z])/g, '$1_$2')
      .toUpperCase();
  });

  // Create your generators here
  plop.setGenerator('component', {
    description: 'Create a new React component',
    prompts: [
      {
        type: 'input',
        name: 'name',
        message: 'Component name:',
      },
    ],
    actions: (data) => {
      // eslint-disable-next-line max-len
      // console.log(`Creating component: ${data.name}`, plop.getHelper('upperSnakeCase')(data.name));
      data.name = coverStringCapitalize(data.name);
      data.componentName = coverStringToPascalCase(data.name);
      data.constName = coverStringUpperSnakeCase(data.name);
      return [
        {
          type: 'add',
          path: 'packages/components/View/{{componentName}}/Builder/index.tsx',
          templateFile: 'plop-templates/componentBuider.hbs',
        },
        {
          type: 'add',
          path: 'packages/components/View/{{componentName}}/Viewer/index.tsx',
          templateFile: 'plop-templates/componentViewer.hbs',
        },
        {
          type: 'modify',
          path: 'packages/constants/fields.ts',
          pattern: /(\/\/ generated by code)/g,
          template: "$1\n  {{constName}}: '{{constName}}',",
        },
        {
          type: 'modify',
          path: 'packages/utils/viewFields.tsx',
          pattern: /(\/\/ generated by code available fields)/g,
          template: '$1\n  [FIELD_NAME.{{constName}}]: true,',
        },
        {
          type: 'modify',
          path: 'packages/utils/viewFields.tsx',
          pattern: /(\/\/ generated by code category fields)/g,
          template: '$1\n    FIELD_NAME.{{constName}},',
        },
        {
          type: 'modify',
          path: 'packages/utils/viewFields.tsx',
          pattern: /(\/\/ generated by code import)/g,
          template: "$1\nconst {{componentName}}Viewer = lazy(() => import('@packages/components/View/{{componentName}}/Viewer'));\nconst {{componentName}}Builder = lazy(() => import('@packages/components/View/{{componentName}}/Builder'));",
        },
        {
          type: 'modify',
          path: 'packages/utils/viewFields.tsx',
          pattern: /(\/\/ generated by code view component)/g,
          template: `$1\n  [FIELD_NAME.{{constName}}]: (props: any) => {
    const { modeView, value } = props;

    if (isViewOrDetailMode(modeView)) {
      return <{{componentName}}Viewer {...props} />;
    }

    return <{{componentName}}Builder {...props} />;
  },`,
        },
        {
          type: 'modify',
          path: 'packages/utils/insertJsonToSchema.ts',
          pattern:
            /(\[FIELD_NAME\.DIGITAL_SIGNATURE\]:\s*createViewDigitalSignatureField)/g,
          template: '$1,\n  [FIELD_NAME.{{constName}}]: create{{componentName}}Field',
        },
        {
          type: 'modify',
          path: 'packages/utils/insertJsonToSchema.ts',
          pattern:
            /(import { createModalGetInfo } from '@packages\/schema\/fields\/ModalGetInfoField';)/g,
          template:
            "import { create{{componentName}}Field } from '@packages/schema/fields/{{componentName}}Field';\n$1",
        },
        {
          type: 'modify',
          path: 'packages/assets/icons/index.ts',
          pattern: /^(.*)/,
          template: "import {{componentName}}Icon from './question.svg';\n$1",
        },
        {
          type: 'modify',
          path: 'packages/assets/icons/index.ts',
          pattern: /(asyncSelectIcon,)/g,
          template: '{{componentName}}Icon,\n  $1',
        },
        {
          type: 'add',
          path: 'packages/schema/fields/{{componentName}}Field/index.ts',
          templateFile: 'plop-templates/componentSchema.hbs',
        },
      ];
    },
  });
}
