export const DATE_FORMAT = {
  DD_MM_YYYY: 'DD-MM-YYYY',
  dd_MM_YYYY: 'dd-MM-YYYY',
  YYYY_MM_DD: 'YYYY-MM-DD',
  YYYY_MM_dd: 'YYYY-MM-dd',
  DDMMYYYY: 'DD/MM/YYYY',
  ddMMYYYY: 'dd/MM/YYYY',
  YYYYMMDD: 'YYYY/MM/DD',
  YYYYMMdd: 'YYYY/MM/dd',
  YYYY: 'YYYY',
  MM_YYYY: 'MM/YYYY',
  MM_YYYY_DASH: 'MM-YYYY',
};

export const DATE_TIME_FORMAT = {
  DD_MM_YYYY_HH_mm_ss: `${DATE_FORMAT.DD_MM_YYYY} HH:mm:ss`,
  dd_MM_YYYY_HH_mm_ss: `${DATE_FORMAT.dd_MM_YYYY} HH:mm:ss`,
  DDMMYYYY_HH_mm_ss: `${DATE_FORMAT.DDMMYYYY} HH:mm:ss`,
  ddMMYYYY_HH_mm_ss: `${DATE_FORMAT.ddMMYYYY} HH:mm:ss`,
  YYYY_MM_DD_HH_mm_ss: `${DATE_FORMAT.YYYY_MM_DD} HH:mm:ss`,
  YYYY_MM_dd_HH_mm_ss: `${DATE_FORMAT.YYYY_MM_dd} HH:mm:ss`,
  YYYYMMDD_HH_mm_ss: `${DATE_FORMAT.YYYYMMDD} HH:mm:ss`,
  YYYYMMdd_HH_mm_ss: `${DATE_FORMAT.YYYYMMdd} HH:mm:ss`,
  YYYY_HH_mm_ss: `${DATE_FORMAT.YYYY} HH:mm:ss`,
  DD_MM_YYYY_HH_mm: `${DATE_FORMAT.DD_MM_YYYY} HH:mm`,
  dd_MM_YYYY_HH_mm: `${DATE_FORMAT.dd_MM_YYYY} HH:mm`,
  DDMMYYYY_HH_mm: `${DATE_FORMAT.DDMMYYYY} HH:mm`,
  ddMMYYYY_HH_mm: `${DATE_FORMAT.ddMMYYYY} HH:mm`,
  YYYY_MM_DD_HH_mm: `${DATE_FORMAT.YYYY_MM_DD} HH:mm`,
  YYYY_MM_dd_HH_mm: `${DATE_FORMAT.YYYY_MM_dd} HH:mm`,
  YYYYMMDD_HH_mm: `${DATE_FORMAT.YYYYMMDD} HH:mm`,
  YYYYMMdd_HH_mm: `${DATE_FORMAT.YYYYMMdd} HH:mm`,
  YYYY_HH_mm: `${DATE_FORMAT.YYYY} HH:mm`,
};
