export const listkeyCaNhan = [
  {
    key: 'Họ và tên',
    value: 'Title',
    valueCSDL: 'HoVaTen',
    id: '_odf8o17AnI1',
    serverPayloadKey: 'CaNhan_ToChuc_Ten',
  },
  {
    key: 'Số CMND/Hộ chiếu',
    value: 'SoCMTND',
    valueCSDL: 'SoCMND',
    id: '_odf8o17AnI2',
    serverPayloadKey: 'CaNhan_ToChuc_CMNDNguoiNopHoSo',
  },
  {
    key: 'Ngày cấp',
    value: 'NgayCapCMTND',
    id: '_odf8o17An3I',
    serverPayloadKey: 'CaNhan_ToChuc_NgayCap',
  },
  {
    key: 'Nơi cấp',
    value: 'NoiCapCMTND',
    id: '_odf8o17AnfI',
    serverPayloadKey: 'CaNhan_ToChuc_NoiCap',
  },
  {
    key: 'Số điện thoại',
    value: 'SoDienThoai',
    id: '_odf8of17AnI',
    serverPayloadKey: 'CaNhan_ToChuc_SoDienThoai',
  },
  {
    key: 'Email',
    value: 'ThuDienTu',
    valueCSDL: 'Email',
    id: '_odf8o417AnI',
    serverPayloadKey: 'CaNhan_ToChuc_EmailNguoiNop',
  },
  {
    key: 'Fax',
    value: 'Fax',
    id: '_odff8o17AnI',
    serverPayloadKey: 'CaNhan_ToChuc_Fax',
  },
  {
    key: 'Địa chỉ',
    value: 'addressDoDac',
    valueCSDL: 'addressDoDac',
    id: '_odf8o417AnI',
    serverPayloadKey: 'CaNhan_ToChuc_DiaChi',
  },
];

export const listkeyToChuc = [
  {
    key: 'Tên tổ chức',
    value: 'Title',
    valueCSDL: 'NAME',
    id: '_odf8o17AnI1',
    serverPayloadKey: 'CaNhan_ToChuc_Ten',
  },
  {
    key: 'Mã số thuế',
    value: 'MaSoThue',
    valueCSDL: 'ENTERPRISE_GDT_CODE',
    id: '_odf8o17AnI1',
    serverPayloadKey: 'CaNhan_ToChuc_MaSoThue',
  },
  {
    key: 'Số GPĐKKD/Số QĐ thành lập',
    value: 'MaSoDoanhNghiep',
    valueCSDL: 'IMP_BUSINESS_CODE',
    id: '_odf8o17AnI2',
    serverPayloadKey: 'CaNhan_ToChuc_MaSoDoanhNghiep',
  },
  {
    key: 'Ngày cấp',
    value: 'NgayCap',
    id: '_odf8o17An3I',
    serverPayloadKey: 'CaNhan_ToChuc_NgayCap',
  },
  {
    key: 'Nơi cấp',
    value: 'NoiCap',
    id: '_odf8o17AnfI',
    serverPayloadKey: 'CaNhan_ToChuc_NoiCap',
  },
  {
    key: 'Số điện thoại',
    value: 'SoDienThoai',
    id: '_odf8of17AnI',
    serverPayloadKey: 'CaNhan_ToChuc_SoDienThoai',
  },
  {
    key: 'Email',
    value: 'ThuDienTu',
    valueCSDL: 'Email',
    id: '_odf8o417AnI',
    serverPayloadKey: 'CaNhan_ToChuc_EmailNguoiNop',
  },
  {
    key: 'Fax',
    value: 'Fax',
    id: '_odff8o17AnI',
    serverPayloadKey: 'CaNhan_ToChuc_Fax',
  },
  {
    key: 'Địa chỉ',
    value: 'addressDoDac',
    valueCSDL: 'AddressFullText',
    id: '_odf8o417AnI',
    serverPayloadKey: 'CaNhan_ToChuc_DiaChi',
  },
  {
    key: 'Người đại diện',
    value: 'NguoiDaiDien.HoVaTen', // TODO: ?
    valueCSDL: 'NguoiDaiDien',
    id: '_odf8o417AnI',
    serverPayloadKey: 'CaNhan_ToChuc_NguoiDaiDien', // TODO: ?
  },
  {
    key: 'Chức vụ',
    value: 'NguoiDaiDien.ChucVu',
    valueCSDL: 'ChucVu',
    id: '_odf8o417AnI',
    serverPayloadKey: 'CaNhan_ToChuc_ChucVu',
  },
];

export const MOCK_CA_NHAN_INFO = {

  LoaiDoiTuong: {
    Loai: 0,
  },
  FileSystemObjectType: 0,
  Id: 15,
  ServerRedirectedEmbedUri: null,
  ServerRedirectedEmbedUrl: '',
  ContentTypeId: '0x0100B97426E3576215489C2646153A704A12',
  Title: 'Hò Văn Tèn',
  DanTocId: null,
  Ho: 'Hò',
  TenDangNhap: 'cn_haihoan1352',
  TenDem: 'Văn',
  Ten: 'Tèn',
  SoCMTND: '131298572',
  NgayCapCMTND: null,
  NoiCapCMTNDId: null,
  SoDienThoai: null,
  NgaySinh: '1979-02-27T17:00:00Z',
  GioiTinh: 'Nam',
  NoiOHienTai_TinhThanhId: null,
  NoiOHienTai_QuanHuyenId: null,
  NoiOHienTai_PhuongXaId: null,
  NoiOHienTai_Khac: null,
  DiaChiThuongTru_TinhThanhId: 5,
  DiaChiThuongTru_QuanHuyenId: 68,
  DiaChiThuongTru_PhuongXaId: 785,
  DiaChiThuongTru_Khac: '42 Đội Cấn',
  QuocTichId: null,
  Email: 'haihoan1352@gmail.com',
  Fax: null,
  WebSite: null,
  NguoiDungId: 193,
  NguoiDungStringId: '193',
  TrangThai: 'Đã kích hoạt',
  NgayDangKy: '2017-03-22T02:30:54Z',
  NgayKichHoat: '2017-03-22T02:37:12Z',
  MaKichHoat: '66c14ac8-dd75-427e-aec9-3beb47622154',
  LoaiDoiTuongId: 1,
  DanhSachFile: null,
  ChucVu: null,
  Token: null,
  TechID: null,
  HoVaTen: null,
  LoaiTaiKhoan: null,
  MaTinh: null,
  ComplianceAssetId: null,
  AuthorId: 1073741823,
  ID: 15,
  Modified: '2024-04-25T08:10:06Z',
  Created: '2017-03-22T02:30:54Z',
  EditorId: 458,
  OData__UIVersionString: '1.0',
  Attachments: false,
  GUID: 'a6b059e3-3b13-4268-9920-4fd255765670',

};

export const MOCK_TO_CHUC_INFO = {

  LoaiDoiTuong: {
    Loai: 1,
  },
  FileSystemObjectType: 0,
  Id: 45,
  ServerRedirectedEmbedUri: null,
  ServerRedirectedEmbedUrl: '',
  Title: 'Công ty TNHH Hoàng Kim ',
  TrangThai: 'Đã kích hoạt',
  MaSoThue: '30489456732',
  TenDangNhap: 'tc_HoangKim',
  MaGiayPhep: '781926745',
  NgayCap: '2010-03-07T17:00:00Z',
  NoiCap: 'Sở Kế hoạch và đầu tư Hà Nội',
  NgayDangKy: '2017-03-15T09:45:00Z',
  NgayKichHoat: '2017-03-15T09:46:00Z',
  MaKichHoat: '5736ed63-0ce5-4b5d-ad92-8b26831156a7',
  SoDienThoai: '0978336989',
  LoaiDoiTuongId: 3,
  DiaDiem_TinhThanhId: 5,
  DiaDiem_QuanHuyenId: 68,
  DiaDiem_PhuongXaId: 794,
  DiaDiem_Khac: '12 Láng Hạ',
  Email: 'anhnguyentuan.hd@gmail.com',
  Fax: null,
  WebSite: 'a.com.vn',
  NguoiDungId: 191,
  NguoiDungStringId: '191',
  TrangThaiDoanhNghiepId: 3,
  SoVonKinhDoanh: 0,
  NguoiDaiDienId: 13,
  LoaiHinhDoanhNghiepId: 1,
  DanhSachFile: '[{"FileName":" Giay phep test.pdf","FileSize":707693,"FileType":"application/pdf","FileIndex":1,"PhysicalName":"","NodeId":"ea49fa31-21e2-4cac-a17b-998c871eb322","Extension":"","FileTitle":"1609GKVB"}]',
  Token: null,
  TenTiengAnh: 'Hoang Kim Limited company',
  TenVietTat: 'Hoang Kim Lmt Co',
  ContentTypeId: '0x0100E0C62F0D85BF514E91B72A4D56356A9D',
  TechID: null,
  TenDoanhNghiep: null,
  ComplianceAssetId: null,
  ID: 45,
  Modified: '2024-01-22T09:07:02Z',
  Created: '2017-03-15T09:45:56Z',
  AuthorId: 1073741823,
  EditorId: 128,
  OData__UIVersionString: '1.0',
  Attachments: false,
  GUID: '1c7e9c4d-c1e6-4a24-bc89-d9fcdd6c3d2d',

};

export const allListKey = [...listkeyCaNhan, ...listkeyToChuc];
